### ISSUE TITLE
Gestión de ficheros

### ISSUE THREAD

**Issue by davizinho5** [aigora/twE100_2122-latam#6]
Debéis definir el **formato de los ficheros** que vuestro programa genera y lee (por ejemplo, el [formato CSV](https://es.wikipedia.org/wiki/Valores_separados_por_comas) es muy común para almacenar datos), y debéis **implementar el código** necesario para generar y leer estos ficheros.
Esta implementación puede tener cambios en la versión definitiva.

**Comment by reginagomez** [comment]
#include <stdio.h>
int main ()
{
    char usuario [30];
    char contrase [30];
    FILE *iniciosesion;
    iniciosesion=fopen ("INICIOSESION.txt", "w");
    printf ("introduzca su usuario\n");
    scanf ("%s", usuario);
    printf("introduzca su contrasena\n");
    scanf ("%s", contrase);
    fprintf (iniciosesion, "USUARIO\n CONTRASEÑA\t");
    fprintf(iniciosesion, "%s\n", usuario);
    fprintf(iniciosesion, "%s", contrase);

    fclose (iniciosesion);
    return 0;
}

**Comment by reginagomez** [comment]
#include <stdio.h>
int main ()
{
    char nombre [30];
    int fecha ;
    FILE *iniciosesionfecha;
    iniciosesionfecha=fopen ("INICIOSESIONfecha.txt", "w");
    printf ("introduzca su nombre\n");
    scanf ("%s", nombre);
    printf("introduzca su fecha de nacimiento sin guiones ni espacios (diamesaño)\n");
    scanf ("%s", fecha);
    fprintf (iniciosesionfecha, "USUARIO\n FECHA\t");
    fprintf(iniciosesionfecha, "%s\n", nombre);
    fprintf(iniciosesionfecha, "%i", fecha);

    fclose (iniciosesionfecha);
    return 0;
}
