### ISSUE TITLE
Diagrama de flujo

### ISSUE THREAD

**Issue by davizinho5** [aigora/twE100_2122-latam#7]
Debéis crear un fichero en formato [PDF](https://help.github.com/en/articles/rendering-pdf-documents), [GIF, JPEG o PNG](https://help.github.com/en/articles/rendering-and-diffing-images) (**no se admiten documentos Word o similar**) representando el [diagrama de flujo](https://es.wikipedia.org/wiki/Diagrama_de_flujo) previsto para vuestro programa. 
En el punto de inicio tenéis un [tutorial](https://github.com/aigora/punto_inicio/wiki/6.1-C%C3%B3mo-realizar-un-diagrama-de-flujo) para crear diagramas de flujo.
Este diagrama os servirá de guía para la implementación del trabajo. No obstante, ésta será la primera versión, por lo que según vayáis avanzando en el desarrollo del programa podréis y deberéis modificarlo.

**Comment by reginagomez** [comment]
![Untitled Diagram drawio (1)](https://user-images.githubusercontent.com/61050089/166118919-9f223bf1-bcfc-46bb-b436-54956eaa44b5.png)

**Comment by reginagomez** [comment]
![Untitled Diagram (2)](https://user-images.githubusercontent.com/61050089/168147011-3917b6d3-f6f9-4181-a3bf-99cc53fca70d.jpg)

**Comment by reginagomez** [comment]
![diagrama final](https://user-images.githubusercontent.com/61050089/170788247-53a0d9c2-9bc0-4113-af86-fe9d2b534075.jpg)

**Comment by reginagomez** [comment]
![diagrama final](https://user-images.githubusercontent.com/61050089/170788370-fccdbe08-6e12-4340-99ae-3d556ac0400a.jpg)

**Comment by reginagomez** [comment]
![diagrama final](https://user-images.githubusercontent.com/61050089/170789124-1d74bfe5-678d-4253-b9b4-2d3bbb4ac7f2.png)
